# -*- coding: utf-8 -*-
"""Crawl_LinkedIn_Profiles_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQL_Lq11Z7hEZuXp7pzBwqlJTek3g11W
"""

# @title 1. Cài đặt Google Chrome Stable & Thư viện
# Cài đặt các thư viện Python cần thiết
!pip install selenium webdriver-manager gspread pandas

# Cài đặt Google Chrome Stable chính chủ (Tránh lỗi Snap của Chromium)
!wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
!sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
!apt-get -y update
!apt-get install -y google-chrome-stable

print("✅ Đã cài đặt Google Chrome Stable thành công!")

# @title 🚀 FINAL FIX: Title & Location (Deep Scan Mode)
import os
import time
import pickle
import random
import gspread
import re
from google.auth import default
from google.colab import auth, files
from IPython.display import Image, display

# Selenium Imports
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# --- CẤU HÌNH ---
COOKIES_FILE = 'linkedin_cookies.pkl'
SHEET_ID_OR_URL = 'https://docs.google.com/spreadsheets/d/1OhjIaXVwbO3x_Iu07h3s5fJzzXO1SezOw1K_Hl7LtOc/edit?gid=0#gid=0'
INPUT_TAB_NAME = "Sheet1"

# TÀI KHOẢN
USERNAME = "ray@sam-foundation.org"
PASSWORD = "passnotE@1234"

# --- 1. SETUP DRIVER ---
def setup_driver():
    options = webdriver.ChromeOptions()
    options.add_argument('--headless=new')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument("--window-size=1920,1080")
    options.add_argument("--lang=en-US")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36")

    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=options)
    return driver

# --- 2. KẾT NỐI GOOGLE SHEET ---
def connect_google_sheet():
    try:
        auth.authenticate_user()
        creds, _ = default()
        gc = gspread.authorize(creds)
        sh = gc.open_by_url(SHEET_ID_OR_URL) if "http" in SHEET_ID_OR_URL else gc.open_by_key(SHEET_ID_OR_URL)
        return sh
    except Exception as e:
        print(f"⚠️ Lỗi kết nối Sheet: {e}")
        return None

# --- 3. LOGIN ---
def login_linkedin(driver):
    driver.get("https://www.linkedin.com/login")
    if os.path.exists(COOKIES_FILE):
        with open(COOKIES_FILE, "rb") as f:
            for cookie in pickle.load(f):
                try: driver.add_cookie(cookie)
                except: pass
        driver.refresh()
        time.sleep(5)
    if "feed" in driver.current_url: return True

    try:
        WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "username"))).send_keys(USERNAME)
        driver.find_element(By.ID, "password").send_keys(PASSWORD)
        driver.find_element(By.XPATH, "//button[@type='submit']").click()
        time.sleep(10)
        with open(COOKIES_FILE, "wb") as f:
            pickle.dump(driver.get_cookies(), f)
        return True
    except: return False

# --- 4. CRAWL PROFILE (HÀM FIX TRIỆT ĐỂ) ---
def crawl_profile(driver, raw_url):
    try:
        url = raw_url.strip()
        driver.get(url)

        print(f"--- Processing: {url}")
        time.sleep(random.uniform(20, 35))

        # Cuộn trang nhiều lần để kích hoạt dữ liệu ẩn
        for _ in range(3):
            driver.execute_script("window.scrollBy(0, 300);")
            time.sleep(1)

        if any(x in driver.current_url for x in ["login", "authwall", "checkpoint", "challenge"]):
            print("Debug: Auth wall detected.")
            # Chụp screenshot
            filename = f"authwall_{int(time.time())}.png"
            driver.save_screenshot(filename)

            # Hiển thị ảnh trong Colab
            from IPython.display import Image, display
            display(Image(filename))
            return None, "AUTH_WALL"

        data_js = driver.execute_script("""
            const getCleanText = (el) => el ? el.innerText.split('\\n')[0].trim() : "";

            let companies = [];
            const topCardElements = document.querySelectorAll('.pv-text-details__right-panel li, button[aria-label*="Current company"], [data-test-id="top-card-experience-entity"]');
            topCardElements.forEach(el => {
                let txt = getCleanText(el);
                if (txt && !companies.includes(txt)) companies.push(txt);
            });

            if (companies.length <= 1) {
                const experienceSection = document.querySelector('#experience-section, section.experience-section, #experience');
                const expItems = document.querySelectorAll('.pvs-list__paged-list-item, .pv-profile-section__section-info li');

                expItems.forEach(item => {
                    const dateText = item.innerText.toLowerCase();
                    if (dateText.includes('present') || dateText.includes('hiện tại')) {
                        const compName = item.querySelector('.t-bold span, [class*="company"] span')?.innerText.split('·')[0].trim();
                        if (compName && !companies.includes(compName)) companies.push(compName);
                    }
                });
            }

            return {
                name: document.querySelector('h1')?.innerText?.trim() || "",
                title: document.querySelector('div.text-body-medium.break-words')?.innerText?.trim() ||
                       document.querySelector('p.ea0c7c71._9041d5c0')?.innerText?.trim() || "",
                location: document.querySelector('span.text-body-small.inline.t-black--light.break-words')?.innerText?.trim() ||
                          document.querySelector('p.ea0c7c71._95ef5a8e')?.innerText?.trim() || "",
                company_list: companies.filter(c => c.length > 2).join(" | "),
                connection_raw: document.body.innerText
            };
        """)

        name = data_js.get('name', '')
        title = data_js.get('title', '')
        location = data_js.get('location', '')
        company = data_js.get('company_list', '')
        conn_source = data_js.get('connection_raw', '')

        # # Fallback: Nếu vẫn trống công ty, thử lấy từ Title (thường sau dấu "at")
        # if not company and " at " in title:
        #     company = title.split(" at ")[-1].split("|")[0].strip()

        print(f"Debug: Extracted Name: {name}")
        print(f"Debug: Extracted Companies: {company}")

        connection = ""
        match = re.search(r'([\d,\.\+]+)\s*(connections|kết nối|followers|người theo dõi)', conn_source, re.I)
        if match:
            connection = match.group(0)

        print(f"Debug: Stats - Title: {len(title)} chars, Loc: {len(location)} chars, Comp: {len(company)} chars")

        return {
            "Name": name, "Title": title, "Location": location, "Connection": connection, "Company": company
        }, "Success"

    except Exception as e:
        print(f"Debug: Error at {url} - {str(e)}")
        return None, str(e)

# --- 5. MAIN ---
def main():
    MAX_PROFILE = 20
    count = 0
    sh = connect_google_sheet()
    if not sh: return
    ws = sh.worksheet(INPUT_TAB_NAME)
    urls = ws.col_values(1)

    driver = setup_driver()
    if not login_linkedin(driver): return

    for i in range(1, len(urls)):
        url = urls[i]
        if "linkedin.com/in/" not in url: continue

        print(f"🔄 Đang xử lý: {url}")
        data, status = crawl_profile(driver, url)

        if data and data['Name']:
            print(f"   ✅ OK: {data['Name']} | {data['Location']} | {data['Title']}, {data['Connection']}, {data['Company']}")
            ws.update(range_name=f"B{i+1}:F{i+1}", values=[[
                data['Name'], data['Title'], data['Location'], data['Connection'], data['Company']
            ]])
        else:
            print(f"   ❌ Lỗi: {status}")
            ws.update_cell(i+1, 2, f"Error: {status}")
            if status == "AUTH_WALL": break

        count +=1
        if count >= MAX_PROFILE:
            print("reached max limit")
            break

        time.sleep(random.randint(40, 80))

    driver.quit()

if __name__ == "__main__":
    main()
    print("✅ Done!")